body.o: body.c ../include/body.h ../include/vector.h \
 ../include/collisions.h ../include/mgl_callback.h
collisions.o: collisions.c ../include/collisions.h ../include/vector.h
entity.o: entity.c ../include/entity.h ../include/obj.h \
 ../include/model.h ../include/sprite.h ../include/graphics3d.h \
 ../include/vector.h ../include/collisions.h ../include/body.h \
 ../include/mgl_callback.h ../include/simple_logger.h
gametest3d.o: gametest3d.c ../include/mgl_callback.h \
 ../include/simple_logger.h ../include/graphics3d.h ../include/shader.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/vector.h ../include/vector.h \
 ../include/sprite.h ../include/entity.h ../include/obj.h \
 ../include/collisions.h ../include/body.h ../include/mgl_callback.h \
 ../include/space.h
graphics3d.o: graphics3d.c ../include/graphics3d.h \
 ../include/simple_logger.h ../include/shader.h
mgl_callback.o: mgl_callback.c ../include/mgl_callback.h
model.o: model.c ../include/simple_logger.h ../include/model.h \
 ../include/sprite.h ../include/graphics3d.h ../include/vector.h
obj.o: obj.c ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/vector.h ../include/simple_logger.h
shader.o: shader.c ../include/shader.h ../include/simple_logger.h
simple_logger.o: simple_logger.c ../include/simple_logger.h
space.o: space.c ../include/space.h ../include/body.h ../include/vector.h \
 ../include/collisions.h ../include/mgl_callback.h ../include/body.h \
 ../include/simple_logger.h
sprite.o: sprite.c ../include/sprite.h ../include/graphics3d.h \
 ../include/simple_logger.h ../include/graphics3d.h
vector.o: vector.c ../include/vector.h
